### ISSUE TITLE
KeyError: 'inventoryInfo'

### ISSUE THREAD

**Issue by Rod-fish** [jmkl009/PalworldCharacterTransfer#19]
palserver update 
Currently not functioning, here is the error message:
```
found instance
Found Character Parameter Map
Read 473 pals from source save
Searching for container data
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "char-export-zh.py", line 540, in main
KeyError: 'inventoryInfo'
```

**Comment by jmkl009** [comment]
I have pushed a fix, but I am not sure if this is fully compatible with the current version. If you can run python, you can try python char-export.py to help me test it.

**Comment by MelonFruitbowl** [comment]
Issue still occurs after grabbing the new build:

found instance
Found Character Parameter Map
Read 290 pals from source save
Searching for container data
Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "PalworldCharacterTransfer-main\char-export.py", line 540, in main
    inv_info = host_json["SaveData"]["value"]["InventoryInfo"]["value"]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'InventoryInfo'

**Comment by jmkl009** [comment]
I have not updated char-export-zh.py, use char-export.py for now

**Comment by ChenxinWang** [comment]
I am able to find "inventoryInfo" in my .sav file, so I need to modify "inv_info = host_json["SaveData"]["value"]["inventoryInfo"]["value"]" to remain as "inv_info = host_json["SaveData"]["value"]["inventoryInfo"]["value"]". The opposite situation should be similar.
