### ISSUE TITLE
Character Transfer Failed

### ISSUE THREAD

**Issue by patchell13** [jmkl009/PalworldCharacterTransfer#20]
Getting following when trying to transfer:

found instance
Found Character Parameter Map
Read 25 pals from source save
Searching for container data
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "char-export.py", line 540, in main
KeyError: 'inventoryInfo'

**Comment by jmkl009** [comment]
I have pushed a fix, but I am not sure if this is fully compatible with the current version. If you can run python, you can try python char-export.py to help me test it.

**Comment by NaxosOne** [comment]
Hello @jmkl009,
There is still an error, even with the InventoryInfo : 

    inv_info = host_json["SaveData"]["value"]["InventoryInfo"]["value"]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'InventoryInfo'

**Comment by MelonFruitbowl** [comment]
> I have pushed a fix, but I am not sure if this is fully compatible with the current version. If you can run python, you can try python char-export.py to help me test it.

On line 540 the i in inventoryInfo is capitalized. Uncapitalizing it fixes the issue.

**Comment by jmkl009** [comment]
The newer version save files use capitalized “i”

**Comment by MelonFruitbowl** [comment]
> The newer version save files use capitalized “i”

Ahh ok I think the error then is stemming from the fact we are trying to use an old player sav file and writing to a new player sav file. It isnt able to us the Capital I because the old one uses the lowercase.

**Comment by filav99** [comment]
@MelonFruitbowl Did you solved it?

**Comment by jmkl009** [comment]
Fixed now
